export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const CREATE_SESSION = "CREATE_SESSION";
export const DELETE_SESSION = "DELETE_SESSION";

export const FOLLOW_USER = "FOLLOW_USER";
export const FETCH_USER_SUGGESTION = 'FETCH_USER_SUGGESTION'
export const POST_USER_SUGGESTION = 'POST_USER_SUGGESTION';

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILED = "PROFILE_FAILED";

export const FETCH_USER_DETAIL_LOADING = "FETCH_USER_DETAIL_LOADING";
export const FETCH_USER_DETAIL_SUCCESS = "FETCH_USER_DETAIL_SUCCESS";

export const PROFILE_REPLIES_LOADING = "PROFILE_REPLIES_LOADING";
export const PROFILE_REPLIES_SUCCESS = "PROFILE_REPLIES_SUCCESS";
export const PROFILE_REPLIES_FAILED = "PROFILE_REPLIES_FAILED";

export const PROFILE_LIKES_LOADING = "PROFILE_LIKES_LOADING";
export const PROFILE_LIKES_SUCCESS = "PROFILE_LIKES_SUCCESS";
export const PROFILE_LIKES_FAILED = "PROFILE_LIKES_FAILED";

export const POST_LOADING = 'POST_LOADING';
export const POST_FAILED = 'POST_FAILED';
export const POST_SUCCESS = 'POST_SUCCESS';

export const COMMENT_LOADING = 'COMMENT_LOADING';
export const COMMENT_FAILED = 'COMMENT_FAILED';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS'; 

export const POST_TWEET = 'POST_TWEET';
export const POST_TWEET_LOADING = 'POST_TWEET_LOADING';
export const POST_TWEET_SUCCESS = 'POST_TWEET_SUCCESS';
export const POST_TWEET_FAILED = 'POST_TWEET_FAILED';

export const POST_COMMENT = 'POST_COMMENT';
export const POST_COMMENT_LOADING = 'POST_COMMENT_LOADING';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAILED = 'POST_COMMENT_FAILED';

export const POST_LIKE_LOADING = 'POST_LIKE_LOADING';
export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS';
export const POST_LIKE_FAILED = 'POST_LIKE_FAILED';

export const __FETCH_TWEET_LOADING = '__FETCH_TWEET_LOADING';
export const __FETCH_TWEET_FAILED = '__FETCH_TWEET_FAILED';
export const __FETCH_TWEET_SUCCESS = '__FETCH_TWEET_SUCCESS';

export const __POST_LOADING = '__POST_LOADING';
export const __POST_FAILED = '__POST_FAILED';
export const __POST_SUCCESS = '__POST_SUCCESS';

export const __COMMENT_LOADING = '__COMMENT_LOADING';
export const __COMMENT_FAILED = '__COMMENT_FAILED';
export const __COMMENT_SUCCESS = '__COMMENT_SUCCESS';

export const __LIKE_LOADING = '__LIKE_LOADING';
export const __LIKE_FAILED = '__LIKE_FAILED';
export const __LIKE_SUCCESS = '__LIKE_SUCCESS';