export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const CREATE_SESSION = "CREATE_SESSION";
export const DELETE_SESSION = "DELETE_SESSION";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILED = "PROFILE_FAILED";

export const POST_LOADING = 'POST_LOADING';
export const POST_FAILED = 'POST_FAILED';
export const POST_SUCCESS = 'POST_SUCCESS';

export const COMMENT_LOADING = 'COMMENT_LOADING';
export const COMMENT_FAILED = 'COMMENT_FAILED';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS'; 

export const POST_TWEET = 'POST_TWEET';
export const POST_TWEET_LOADING = 'POST_TWEET_LOADING';
export const POST_TWEET_SUCCESS = 'POST_TWEET_SUCCESS';
export const POST_TWEET_FAILED = 'POST_TWEET_FAILED';

export const POST_COMMENT = 'POST_COMMENT';
export const POST_LIKE = 'POST_LIKE';