export const POST_LOADING = 'POST_LOADING';
export const POST_FAILED = 'POST_FAILED';
export const POST_SUCCESS = 'POST_SUCCESS';

export const COMMENT_LOADING = 'COMMENT_LOADING';
export const COMMENT_FAILED = 'COMMENT_FAILED';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS'; 

export const POST_TWEET = 'POST_TWEET';
export const POST_TWEET_LOADING = 'POST_TWEET_LOADING';
export const POST_TWEET_SUCCESS = 'POST_TWEET_SUCCESS';
export const POST_TWEET_FAILED = 'POST_TWEET_FAILED';

export const POST_COMMENT = 'POST_COMMENT';
export const POST_LIKE = 'POST_LIKE';